version: "3.9"

services:
  dc-user-db:
    image: "mongo"
    command: mongod --port 27017
    container_name: dc-user-db
    restart: always
    volumes:
      - dbs:/data/user-db
    ports:
      - 27017:27017
    networks:
      - devcrunch

  dc-post-db:
    image: "mongo"
    command: mongod --port 27027
    container_name: dc-post-db
    restart: always
    volumes:
      - dbs:/data/post-db
    ports:
      - 27027:27027
    networks:
      - devcrunch

  dc-comment-db:
    image: "mongo"
    command: mongod --port 27037
    container_name: dc-comment-db
    volumes:
      - dbs:/data/comment-db
    restart: always
    ports:
      - 27037:27037
    networks:
      - devcrunch

  dc-gateway-service:
    restart: always
    build:
      context: ./dc-back-end/dc-gateway-service
    ports: 
      - 10000:10000
    links:
      - dc-eureka-service
      - dc-user-service
      - dc-post-service
      - dc-comment-service
    depends_on:
      - dc-eureka-service
      - dc-user-service
      - dc-post-service
      - dc-comment-service
    environment:
      - EUREKA_SERVICE_HOST=dc-eureka-service
      - EUREKA_SERVICE_PORT=10761
    networks:
      - devcrunch

  dc-eureka-service:
    restart: always
    build:
      context: ./dc-back-end/dc-eureka-service
    ports:
      - 10761:10761
    environment:
      - EUREKA_SERVICE_HOST=localhost
      - EUREKA_SERVICE_PORT=10761
    networks:
      - devcrunch
  
  dc-user-service:
    restart: always
    container_name: dc-user-service
    build:
      context: ./dc-back-end/dc-user-service
    ports:
      - 10010:10010
    links:
      - dc-user-db
    depends_on:
      - dc-eureka-service
    environment:
      - EUREKA_SERVICE_HOST=dc-eureka-service
      - EUREKA_SERVICE_PORT=10761
      - DATABASE_HOST=dc-user-db
      - DATABASE_PORT=27017
    networks:
      - devcrunch

  dc-post-service:
    restart: always
    container_name: dc-post-service
    build:
      context: ./dc-back-end/dc-post-service
    ports:
      - 10020:10020
    links:
      - dc-post-db
    depends_on:
      - dc-eureka-service
    environment:
      - EUREKA_SERVICE_HOST=dc-eureka-service
      - EUREKA_SERVICE_PORT=10761
      - DATABASE_HOST=dc-post-db
      - DATABASE_PORT=27027
    networks:
      - devcrunch
  
  dc-comment-service:
    restart: always
    container_name: dc-comment-service
    build:
      context: ./dc-back-end/dc-comment-service
    ports:
      - 10030:10030
    links:
      - dc-comment-db
    depends_on:
      - dc-eureka-service
    environment:
      - EUREKA_SERVICE_HOST=dc-eureka-service
      - EUREKA_SERVICE_PORT=10761
      - DATABASE_HOST=dc-comment-db
      - DATABASE_PORT=27037
    networks:
      - devcrunch

  # dc-admin:
  #   restart: always
  #   container_name: dc-admin
  #   build:
  #     context: ./dc-front-end/dc-admin
  #   ports:
  #     - 10100
  #   depends_on:
  #     - dc-gateway-service
  #   networks:
  #     - devcrunch

  # dc-client:
  #   restart: always
  #   container_name: dc-client
  #   build:
  #     context: ./dc-front-end/dc-client
  #   ports:
  #     - 10200
  #   depends_on:
  #     - dc-gateway-service
  #   networks:
  #     - devcrunch

volumes:
  dbs:
    
networks:
  devcrunch:
    driver: bridge