server:
    port: 10010

spring:
    application:
        name: dc-user-service
    data:
        mongodb:
            host: ${database.host:localhost}:${database.port:27017}
            database: user-db

eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.service.host:localhost}:${eureka.service.port:10761}/eureka/

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF