server:
    port: 10020

spring:
    application:
        name: dc-post-service
    cloud:
        openfeign:
            client:
                config:
                    commentClient:
                        url: http://${comment.service.host:localhost}:${comment.service.port:10030}/comments/
    data:
        mongodb:
            host: ${database.host:localhost}:${database.port:27017}
            database: post-db

eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.service.host:localhost}:${eureka.service.port:10761}/eureka/

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF