server:
    port: 10030

spring:
    application:
        name: dc-comment-service
    data:
        mongodb:
            host: ${database.host:localhost}:${database.port:27017}
            database: comment-db

eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.service.host:localhost}:${eureka.service.port:10761}/eureka/

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF
