spring:
    application:
        name: dc-eureka-service

server:
    port: ${eureka.service.port:10761}

eureka:
    instance:
        hostname: ${eureka.service.host:localhost}
        preferIpAddress: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF