spring:
    application:
        name: dc-eureka-service

server:
    port: 10761

eureka:
    instance:
        hostname: ${eureka.service.host}
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:10761/eureka/

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF